### ISSUE TITLE
`Requirement.as_line` doesn't work for VCS with extras

### ISSUE THREAD

**Issue by notEvil** [sarugaku/requirementslib#24]
Hi,

as should be obvious from
https://github.com/sarugaku/requirementslib/blob/50e3d7c56072dbc525a04fee526be515ac299736/src/requirementslib/models/requirements.py#L789
for VCS urls the extras are appended, which is not desired. If the url ends with `&subdirectory=path/to/sub/directory` then the line would end with `&subdirectory=path/to/sub/directory[extras]`.

This function is used for instance by pipenv. Could you please look into that?

**Comment by techalchemy** [comment]
This seems like a valid point, good catch! This used to rely on a different logical implementation which I think we stripped out. Basically nobody reports anything about subdirectory fragments so we never get feedback if things are broken

**Comment by notEvil** [comment]
Thx, I tried to implement a real fix but was completely lost in code. So I implemented a quick fix instead (using regex) which I don't want to share ^^

Imo there are two things that make the code less readable: there is a lot of code hidden in properties, and inheritance is mixed with nested classes, e.g. BaseRequirement, Requirement

**Comment by techalchemy** [comment]
Agreed. The nested inheritance isn’t a design decision, just needs to be refactored. The properties are there to keep the interfaces clean (although some are probably complex, depending which ones you were looking at they could easily also fit the ‘need to be refactored now’ criteria).

This logic used to be handled in a singular function or two in pipenv where we basically just kept converting things from strings to requirements to pipfile entries and back over and over again. That was the main goal of this library — to give a better and more consistent way of handling that while separating the logic needed for the different kinds of requirements (because modifying them when they weren’t separated caused lots of issues)

**Comment by techalchemy** [comment]
hm can you give me an example of something this actually handles incorrectly?
