### ISSUE TITLE
Editable package wtih ref using @ is not supported properly

### ISSUE THREAD

**Issue by jxltom** [sarugaku/requirementslib#74]
Package such as ```requests = {git = "https://github.com/requests/requests.git@883caaf", editable = true}``` will be parsed to followings in ```pipfile_entry```.

```
"requests": {
            "editable": true,
            "git": "https://github.com/requests/requests.git@883caaf",
            "ref": "883caaf145fbe93bd0d208a6b864de9146087312"
        }
```

But the correct format should be:
```
"requests": {
            "editable": true,
            "git": "https://github.com/requests/requests.git@883caaf145fbe93bd0d208a6b864de9146087312",
        }
```
or 
```
"requests": {
            "editable": true,
            "git": "https://github.com/requests/requests.git",
            "ref": "883caaf145fbe93bd0d208a6b864de9146087312"
        }
```

This makes ```pipenv install``` failed since ```-e git+https://github.com/requests/requests.git@883caaf@883caaf145fbe93bd0d208a6b864de9146087312#egg=pytest``` doesn't exist actually.

**Comment by techalchemy** [comment]
`requests = {git = "https://github.com/requests/requests.git@883caaf", editable = true}`

is something you would have had to add by hand, since the parser will split it up into a `ref` entry in your pipfile also -- or it should

Editable installs are semi-broken for the next few minutes anyway until I cut this release
